// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYD523FZkki9WYOb0TmrIMkg4dutVCyn0',
    appId: '1:855769139538:web:4b2df560bbd8b5d4f5128b',
    messagingSenderId: '855769139538',
    projectId: 'sozlukfire',
    authDomain: 'sozlukfire.firebaseapp.com',
    storageBucket: 'sozlukfire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu54PfB7gAQ_Y4VTBwz2xK7uWQLMz3NG0',
    appId: '1:855769139538:android:27febce56c110d8bf5128b',
    messagingSenderId: '855769139538',
    projectId: 'sozlukfire',
    storageBucket: 'sozlukfire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkAceH3BMqWYigjpWBfTvOMfU224htllI',
    appId: '1:855769139538:ios:2f2cb280467247e9f5128b',
    messagingSenderId: '855769139538',
    projectId: 'sozlukfire',
    storageBucket: 'sozlukfire.appspot.com',
    iosClientId: '855769139538-7garbmm45jodnfl8c2mesalro3pm7fnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSozlukFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkAceH3BMqWYigjpWBfTvOMfU224htllI',
    appId: '1:855769139538:ios:2f2cb280467247e9f5128b',
    messagingSenderId: '855769139538',
    projectId: 'sozlukfire',
    storageBucket: 'sozlukfire.appspot.com',
    iosClientId: '855769139538-7garbmm45jodnfl8c2mesalro3pm7fnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSozlukFire',
  );
}
